version: '3.8'

services:
  my-bot:
    build: .             # из текущей папки
    restart: always      # перезапуск вседга
    environment:
      - BOT_NAME=${BOT_NAME}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_API_URL=http://telegram-api:8081/bot
    volumes:
      # это общая папка
      - telegram-data:/var/lib/telegram-bot-api
    depends_on:
      - telegram-api     # запуск ТОЛЬКо после запуска апи сервера

  telegram-api:
    image: aiogram/telegram-bot-api:latest
    restart: always
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_LOCAL=true
    volumes:
      - telegram-data:/var/lib/telegram-bot-api
    ports:
      - "8081:8081" # открытие порта наружу для отладки

# общая папка (том )
volumes:
  telegram-data: