services:
  my-bot:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - BOT_API_URL=http://telegram-api:8081/bot
      - COBALT_API_URL=http://cobalt:9000
    volumes:
      - telegram-data:/var/lib/telegram-bot-api
    depends_on:
      - telegram-api
      - cobalt

  telegram-api:
    image: aiogram/telegram-bot-api:latest
    restart: always
    env_file:
      - .env
    environment:
      - TELEGRAM_LOCAL=true
    volumes:
      - telegram-data:/var/lib/telegram-bot-api
    ports:
      - "8081:8081"

  cobalt:
    image: ghcr.io/imputnet/cobalt:latest
    restart: always
    environment:
      - API_URL=http://cobalt:9000
      - COOKIE_PATH=/app/cookies.json
    ports:
      - "9000:9000"

volumes:
  telegram-data: